name: schic-scvi-3d
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - python==3.8
  - scvi-tools==0.14.5
  - scanpy==1.9.8
  - anndata==0.7.5
  - matplotlib==3.6.0
  - pytorch-lightning==1.3
  - pytorch==1.8.0
  - torchmetrics==0.7.0
  - scikit-learn==0.24.2
